#!/usr/bin/env bash
# Rebuild `main` from a fresh upstream snapshot.
#
# Upstream publishes ~1 squashed snapshot commit per day, so a merge-based fork
# would re-resolve the 2000-file rename on every drop. Instead the rebrand is
# REGENERATED here and can never conflict; only the small feature stack rebases.
#
#   vendor  ---o------------o              pristine upstream snapshots
#               \            \
#                o tooling    o tooling    replayed
#                 \            \
#                  o rebrand    o rebrand  regenerated, never merged
#                   \            \
#                    o-o-o        o-o-o    feature commits, rebased
set -euo pipefail
cd "$(dirname "$0")/.."

TOOLING_SUBJECT='tooling: rebrand codemod, brand gate, upstream sync, docs'
REBRAND_SUBJECT='rebrand: generated by tools/rebrand.py'

if [ -n "$(git status --porcelain)" ]; then
  echo "sync: working tree is dirty; commit or stash first" >&2
  exit 1
fi

find_commit() { git log --format='%H %s' main | grep -F -m1 -- "$1" | cut -d' ' -f1; }

tooling=$(find_commit "$TOOLING_SUBJECT")
rebrand=$(find_commit "$REBRAND_SUBJECT")
if [ -z "$tooling" ] || [ -z "$rebrand" ]; then
  echo "sync: could not locate the tooling and rebrand commits on main" >&2
  exit 1
fi

echo "==> fetching upstream"
git fetch --depth 1 upstream main
new_vendor=$(git rev-parse FETCH_HEAD)
if [ "$(git rev-parse vendor)" = "$new_vendor" ]; then
  echo "sync: vendor already at $(git rev-parse --short "$new_vendor"); nothing to do"
  exit 0
fi

stack=$(git rev-list --count "$rebrand"..main)
echo "==> feature stack: $stack commit(s) to replay"

git branch -f main-backup main
git branch -f vendor "$new_vendor"

# The codemod lives in the tooling commit, so replay that onto the new snapshot
# before running it -- `vendor` alone has no tools/.
echo "==> replaying tooling onto the new snapshot"
git checkout -q --detach vendor
git cherry-pick "$tooling"

echo "==> regenerating the rebrand"
python3 tools/rebrand.py
# The rename reorders imports (bcode_* sorts where xai_* did not), so formatting
# is part of the generated result, not a follow-up fix.
cargo fmt --all
git add -A
git commit -q -m "$REBRAND_SUBJECT"
new_rebrand=$(git rev-parse HEAD)

if [ "$stack" -gt 0 ]; then
  echo "==> replaying feature stack"
  git branch -f main-rebuild "$new_rebrand"
  git rebase --onto main-rebuild "$rebrand" main
  git branch -D main-rebuild
else
  git checkout -q -B main "$new_rebrand"
fi
git checkout -q main

echo "==> verifying"
make verify

echo
echo "sync: main rebuilt on upstream $(git rev-parse --short "$new_vendor")."
echo "      previous main kept as main-backup; 'make clean-backup' drops it."
